---
- name: update web servers
  hosts: web

  tasks: 
   - name: ensure that directory is created
     file:
       path: /home/centos/web
       state: directory

   - name: file is updated
     copy:
       dest: /home/centos/web/web.conf
       content: My webapp config


- name: update app servers
  hosts: app

  tasks:
   - name: ensure that directory is created
     file:
       path: /home/centos/app
       state: directory
   - name: file is updated
     copy:
       dest: /home/centos/app/app.conf
       content: My app config

   
...
