---
- name: update web servers
  hosts: web
  become: yes

  tasks: 
   - name: ensure apache is installed
     package:
       name: httpd
       state: present

   - name: enable apache 
     service:
       name: httpd
       enabled: yes

   - name: start apache 
     service:
       name: httpd
       state: started


...
